### ISSUE TITLE
不支援 Noto Sans CJK Fonts

### ISSUE THREAD

**Issue by laichiaheng** [fcitx/fcitx-chewing#12]
我打了過、骨、化，但是在選字框內的字體和我打出來的字體不一樣

http://i.imgur.com/HTwn0Gw.jpg

http://i.imgur.com/hB9OFGo.jpg

http://i.imgur.com/ROIBUSv.jpg

**Comment by Brli** [comment]
那是輸入法本身的設定，可能你會想去看看fcitx的設定頁面

**Comment by wengxt** [comment]
Just as @Brli said, fcitx uses Sans as its font by default. You can change it with configuration ui ( https://fcitx-im.org/wiki/Integrate_with_Desktop ), or modify ~/.config/fcitx/conf/fcitx-classic-ui.config by hand
