### ISSUE TITLE
Select characters by using number keyboard

### ISSUE THREAD

**Issue by alwayschoco** [fcitx/fcitx-chewing#13]
When I want to choose the characters on the selection pages after selection page1 , if I type the number which I wanted by using number keyboard, the character will be the one on selection page1

But it won't happen if I choose it by using horizontal numbers.

For example: 
If I type 媒(ㄇㄟˊ) at first, and I want to choose 霉(at another selection page)，

the first selection page looks like this
![bug1](https://cloud.githubusercontent.com/assets/17408932/13868483/34b2c322-ed04-11e5-88d1-a0052549e081.PNG)

switch to another selection page like this
![bug2](https://cloud.githubusercontent.com/assets/17408932/13868485/37b2394a-ed04-11e5-9d74-d351f51dff62.PNG)

If I choose 霉 by using number keyboard on the right side of keyboard, the result will be 眉 which is on the first page
![bug3](https://cloud.githubusercontent.com/assets/17408932/13868487/3b01ea0a-ed04-11e5-8ebe-1bd96fa6e7db.PNG)

But if I try it by using the horizontal number keys, the result will be correct
![bug4](https://cloud.githubusercontent.com/assets/17408932/13868488/3d6cda20-ed04-11e5-9480-107590cc4e9d.PNG)

**Comment by taylorchu** [comment]
what does "horizontal number" mean?
Thanks.
