### ISSUE TITLE
fcitx chewing 在右方數字鍵無法選字

### ISSUE THREAD

**Issue by Joy55555** [fcitx/fcitx-chewing#17]
我在 ubuntu 14.04 安裝 fcitx 
在使用新酷音選字時，無法使用鍵盤右方數字鍵選擇第二、三頁相對應的字，反而是顯示出第一頁相對應的字；使用鍵盤上方數字鍵是可以選第二頁的字

請問這有設定可以改嗎 ?

謝謝！

**Comment by Joy55555** [comment]
發現已有人提出相同的問題 #13 
想請問，我該如何改我的設定 src/eim.c ?

**Comment by wengxt** [comment]
这个之前提到已经修复了
